
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Return the cached host list (populated at startup / on reload, tech-gui.md §4.2).
 */
async listHosts() : Promise<Result<HostDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_hosts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reload hosts from the shared config, refresh the cache, restart the pollers,
 * and broadcast the new list via `hosts-loaded` (tech-gui.md §4.2). Also the
 * startup entry point: the frontend calls it once its event bridge is up.
 */
async reloadHosts() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reload_hosts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List saved snippets from the shared `snippets.toml` (tech-gui.md §4.2).
 */
async listSnippets() : Promise<Result<SnippetDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_snippets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Upsert a snippet by name and persist the whole list (tech-gui.md §4.2). A new
 * name appends; an existing name is replaced in place (an in-place edit). A rename
 * is a frontend delete-old + save-new, since the contract keys snippets on `name`.
 */
async saveSnippet(snippet: SnippetDto) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_snippet", { snippet }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete the snippet named `name` and persist (tech-gui.md §4.2). A missing name is
 * a no-op success — the desired end state (absent) already holds.
 */
async deleteSnippet(name: string) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_snippet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Execute a snippet on one or more hosts (tech-gui.md §4.2). Substitutes the
 * provided values into declared placeholders, then fires one task per host that
 * runs the command over a fresh SSH session and emits a `snippet-result` (§4.3).
 * Fire-and-forget: results arrive as events, mirroring the core's own model.
 */
async executeSnippet(snippetName: string, hostNames: string[], params: Partial<{ [key in string]: string }>) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_snippet", { snippetName, hostNames, params }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Open a terminal for `host_name`, streaming raw output into `on_output`. Returns
 * the public session id used by the write/resize/close commands (tech-gui.md §4.2).
 */
async terminalOpen(hostName: string, cols: number, rows: number, onOutput: TAURI_CHANNEL<TerminalBytes>) : Promise<Result<number, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_open", { hostName, cols, rows, onOutput }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send keystrokes / pasted bytes to a terminal (tech-gui.md §4.2). Input is
 * low-volume, so the ordinary `number[]` path is fine here (only output is raw).
 */
async terminalWrite(sessionId: number, data: number[]) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_write", { sessionId, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reflow a terminal to `cols` x `rows` (tech-gui.md §4.2).
 */
async terminalResize(sessionId: number, cols: number, rows: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_resize", { sessionId, cols, rows }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Close a terminal and its connection (tech-gui.md §4.2). The frontend has already
 * dropped the tab, so the resulting `PtyExited` emits no `terminal-exited` (§3.4).
 */
async terminalClose(sessionId: number) : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_close", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
error: Error,
hostStatusChanged: HostStatusChanged,
hostsLoaded: HostsLoaded,
metricsUpdated: MetricsUpdated,
servicesDetected: ServicesDetected,
servicesFailed: ServicesFailed,
snippetResult: SnippetResult,
terminalExited: TerminalExited
}>({
error: "error",
hostStatusChanged: "host-status-changed",
hostsLoaded: "hosts-loaded",
metricsUpdated: "metrics-updated",
servicesDetected: "services-detected",
servicesFailed: "services-failed",
snippetResult: "snippet-result",
terminalExited: "terminal-exited"
})

/** user-defined constants **/



/** user-defined types **/

export type CommandError = { message: string }
/**
 * Live connection state for a host (tech-gui.md §4.1). Internally tagged so the
 * frontend consumes a discriminated union keyed on `kind`.
 */
export type ConnectionStatusDto = { kind: "unknown" } | { kind: "connecting" } | { kind: "connected" } | { kind: "failed"; message: string }
/**
 * A background error surfaced to the user.
 */
export type Error = { message: string }
/**
 * A host as the frontend sees it — password and private-key material omitted
 * (tech-gui.md §3.4). `hasKey` reports whether an identity file is configured;
 * the key path itself never crosses the boundary.
 */
export type HostDto = { name: string; hostname: string; user: string; port: number; tags: string[]; notes?: string | null; source: HostSourceDto; hasKey: boolean; passwordAuthDisabled?: boolean | null }
/**
 * Host origin, mirrors `omnyssh_core::ssh::client::HostSource`.
 */
export type HostSourceDto = "sshConfig" | "manual"
/**
 * A host's connection status changed (tech-gui.md §4.3).
 */
export type HostStatusChanged = { hostName: string; status: ConnectionStatusDto }
/**
 * Full host list broadcast. Emitted by `reload_hosts` after refreshing the
 * cache; the bridge does not map `HostsLoaded` (tech-gui.md §3.4).
 */
export type HostsLoaded = HostDto[]
/**
 * A metrics snapshot for a host (tech-gui.md §4.1). The core's `Instant` is
 * flattened to `ageSeconds` (seconds since the sample) so it can serialise.
 */
export type MetricsDto = { cpuPercent?: number | null; ramPercent?: number | null; diskPercent?: number | null; uptime?: string | null; loadAvg?: string | null; osInfo?: string | null; topProcesses: ProcessDto[]; ageSeconds: number }
/**
 * A fresh metrics sample for a host (tech-gui.md §4.3).
 */
export type MetricsUpdated = { hostName: string; metrics: MetricsDto }
/**
 * A single process in the "top processes" panel (tech-gui.md §4.1).
 */
export type ProcessDto = { name: string; cpuPercent: number; memPercent: number }
/**
 * A service detected on a host with its quick-scan metrics (tech-gui.md §4.1).
 */
export type ServiceDto = { kind: ServiceKindDto; metrics: ServiceMetricDto[] }
/**
 * A service kind detected on a host, mirrors `omnyssh_core::event::ServiceKind`.
 * Wire names are lowercase (`docker`, `nginx`, `postgresql`, `redis`, `nodejs`);
 * if the core adds a kind, extend this enum so it is never silently dropped
 * (tech-gui.md §4.1).
 */
export type ServiceKindDto = "docker" | "nginx" | "postgresql" | "redis" | "nodejs"
/**
 * One quick-scan metric for a detected service (tech-gui.md §4.1). `MetricValue`
 * is integer-only today; widen this if the core adds a non-integral variant.
 */
export type ServiceMetricDto = { name: string; value: number }
/**
 * Services detected on a host by the discovery quick-scan (tech-gui.md §4.3).
 */
export type ServicesDetected = { hostName: string; services: ServiceDto[] }
/**
 * Discovery failed for a host (tech-gui.md §4.3).
 */
export type ServicesFailed = { hostName: string; message: string }
/**
 * A saved command snippet as the frontend sees it (tech-gui.md §4.1). Crosses the
 * boundary both ways — outbound for `list_snippets`, inbound for `save_snippet` —
 * so it derives `Deserialize` too. Optional fields are omitted when absent, matching
 * the sparse `snippets.toml` the TUI writes.
 */
export type SnippetDto = { name: string; command: string; scope: SnippetScopeDto; host?: string | null; tags?: string[] | null; params?: string[] | null }
/**
 * Result of running a snippet on one host (tech-gui.md §4.3). Emitted directly by
 * `execute_snippet` per host (one-shot `SshSession::run_command`), not via the
 * shared bridge — the same "the command owns the result" pattern the SFTP
 * per-session forwarder uses (§3.4). The core's `Result<String, String>` is
 * flattened to `ok` + `output` (stdout on success, the error message on failure).
 */
export type SnippetResult = { hostName: string; snippetName: string; ok: boolean; output: string }
/**
 * Snippet scope, mirrors `omnyssh_core::config::snippets::SnippetScope`. Wire
 * names are lowercase (`global`, `host`).
 */
export type SnippetScopeDto = "global" | "host"
/**
 * Raw PTY output bytes for a terminal session's per-session `Channel` (tech-gui.md
 * §3.3/§3.6). Deliberately **not** `Serialize`: that dodges the blanket
 * `Serialize -> IpcResponse` mapping (which would JSON-encode to a slow `number[]`),
 * so the bytes ride the channel as a raw `ArrayBuffer` that xterm writes directly.
 * Only ever sent, never received — the sole non-DTO on the boundary.
 */
export type TerminalBytes = number[]
/**
 * A terminal session's remote shell exited or its connection dropped (tech-gui.md
 * §4.3). Carries the **public** registry id (the bridge maps the core's inner PTY
 * id, §3.4); the frontend tears the tab down. User-initiated closes never emit this.
 */
export type TerminalExited = { sessionId: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
