
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Return the cached host list (populated at startup / on reload, tech-gui.md §4.2).
 */
async listHosts() : Promise<Result<HostDto[], CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_hosts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reload hosts from the shared config, refresh the cache, restart the pollers,
 * and broadcast the new list via `hosts-loaded` (tech-gui.md §4.2).
 */
async reloadHosts() : Promise<Result<null, CommandError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reload_hosts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
error: Error,
hostStatusChanged: HostStatusChanged,
hostsLoaded: HostsLoaded,
metricsUpdated: MetricsUpdated
}>({
error: "error",
hostStatusChanged: "host-status-changed",
hostsLoaded: "hosts-loaded",
metricsUpdated: "metrics-updated"
})

/** user-defined constants **/



/** user-defined types **/

export type CommandError = { message: string }
/**
 * Live connection state for a host (tech-gui.md §4.1). Internally tagged so the
 * frontend consumes a discriminated union keyed on `kind`.
 */
export type ConnectionStatusDto = { kind: "unknown" } | { kind: "connecting" } | { kind: "connected" } | { kind: "failed"; message: string }
/**
 * A background error surfaced to the user.
 */
export type Error = { message: string }
/**
 * A host as the frontend sees it — password and private-key material omitted
 * (tech-gui.md §3.4). `hasKey` reports whether an identity file is configured;
 * the key path itself never crosses the boundary.
 */
export type HostDto = { name: string; hostname: string; user: string; port: number; tags: string[]; notes?: string | null; source: HostSourceDto; hasKey: boolean; passwordAuthDisabled?: boolean | null }
/**
 * Host origin, mirrors `omnyssh_core::ssh::client::HostSource`.
 */
export type HostSourceDto = "sshConfig" | "manual"
/**
 * A host's connection status changed (tech-gui.md §4.3).
 */
export type HostStatusChanged = { hostName: string; status: ConnectionStatusDto }
/**
 * Full host list broadcast. Emitted by `reload_hosts` after refreshing the
 * cache; the bridge does not map `HostsLoaded` (tech-gui.md §3.4).
 */
export type HostsLoaded = HostDto[]
/**
 * A metrics snapshot for a host (tech-gui.md §4.1). The core's `Instant` is
 * flattened to `ageSeconds` (seconds since the sample) so it can serialise.
 */
export type MetricsDto = { cpuPercent?: number | null; ramPercent?: number | null; diskPercent?: number | null; uptime?: string | null; loadAvg?: string | null; osInfo?: string | null; topProcesses: ProcessDto[]; ageSeconds: number }
/**
 * A fresh metrics sample for a host (tech-gui.md §4.3).
 */
export type MetricsUpdated = { hostName: string; metrics: MetricsDto }
/**
 * A single process in the "top processes" panel (tech-gui.md §4.1).
 */
export type ProcessDto = { name: string; cpuPercent: number; memPercent: number }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
